# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"

addons:
  apt:
    packages:
      - graphviz

install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

jdk:
- oraclejdk8

# For TRAVIS_NODE_VERSION, look for the LTS version of node here: https://nodejs.org/en/download/
env:
  global:
    - CI=true
    - TRAVIS_NODE_VERSION="8.9.1"

language: scala

scala:
- 2.11.8

script:
- ./scripts/travis-build.sh
- ./scripts/travis-deploy.sh

